cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/',add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),

]

shop/urls.py
from django.urls import path
from .views import *

# 네임스페이스로 동일하게 사용할 수 있다.
app_name = 'shop'
urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True) 

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-updated']
        index_together = [['id','slug']]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms
# 폼을 쓰는 이유1 : 클라이언트 화면에 입력 폼을 만들어주려고
# 폼을 쓰는 이유2 : 클라이언트가 입력한 데이터에 대한 전처리

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput) # BooleanField에서는 required=False로 해놔야 해.
    # widget=forms.HiddenInput 사용자에게 노출될 때 뭘 쓸건데? 사용자가 보고 고르는 값이 아니라서 hidden으로 넣어주는 것임.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST # 함수형 뷰에 데코레이션을 해주는 기능

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart

@require_POST
def add(request, product_id): # request를 제외한 뒤에 나오는 매개변수들은 주소에 저 내용이 포함되게 넘길거구나.
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    #클라이언트 -> 서버로 데이터를 전달  
    # 유효성 검사, injection 처리
    form = AddProductForm(request.POST) 

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],is_update=cd['is_update'])

    return redirect('cart:detail')

def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)# 제품이 있으면 나오고 없으면 404페이지 띄워.
    cart.remove(product)
    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity':product['quantity'], 'is_update':True})
        
    return render(request, 'cart/detail.html', {'cart':cart})

shop/views.py
from django.shortcuts import render, get_object_or_404 # 해당 모델의 특정 object가 있으면 띄워주고 없으면 404페이지 띄워줌

from .models import *
from cart.forms import AddProductForm

def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True) # 제품을 보여줄 수 있는 애들만 보여주겠다.
    if category_slug:
        current_category = get_object_or_404(Category,slug=category_slug) # 카테고리 모델에서 슬러그가 category_slug인 애를 불러올거야.
        products = products.filter(category=current_category) # products에서 filter를 해서 category가 current_category인 애들을 불러올거야
    return render(request, 'shop/list.html', 
                  {
                      'current_category':current_category,
                      'categories':categories,
                      'products':products,
                      }) # 변수 넣어주면 원하는 데이터를 전부 템플릿으로 넘겨줄 수 있고, 템플릿에서 변수들을 가지고 디스플레이를 하면 돼.

def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    return render(request, 'shop/detail.html', {'product':product, 'add_to_cart':add_to_cart})

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block title %}Product Detail
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <img src="{{ product.image.url }}" width="100%" alt="">
        </div>
        <div class="col">
            <h1 class="display-6">{{ product.name }}</h1>
            <p><span class="badge badge-secondary">Price</span>{{ product.price }}</p>

            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {{ add_to_cart }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary btn-sm" value="Add to Cart">
            </form>

            <h5><span class="badge badge-secondary">Description</span>{{ product.description|linebreaks }}</h5>
        </div>
    </div>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}Category Page
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2">
            <div class="list-group">
                <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">ALL</a>
                {% for c in categories %}
                <a href="{{ c.get_absolute_url }}" class="list-group-item {% if not current_category.slug == c.slug %}active{% endif %}">{{ c.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col">
            <div class="alert alert-info">
                {% if current_category %}{{ current_category.name }}{% else %}All Products{% endif %}
            </div>
            <div class="row">
                {%for product in products %}
                    <div class="col-4">
                        <div class="card">
                            {% if product.image %}<img class="cart-img-top" src="{{ product.image.url}}" alt="Product Image">{% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }} <span class="badge badge-secondary">{{product.price}}</span></p>
                                <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}

{% block style %}
{% endblock %}

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Django Shop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav justify-content-end">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Product</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Cart
                    {% if cart|length > 0 %}
                        ${{ cart.get_product_total }} with {{ cart|length }} items
                    {% else %}
                        : Empty
                    {% endif %}
                </a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="container">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>